rt_DEG <- read.table(file = "/Users/stead/Desktop/GDC/LUAD/DEG/Ttest_DEG_fp.txt", header = T, row.names = NULL, sep = "\t" )
rt_T <- read.table(file = "/Users/stead/Desktop/GDC/LUAD/merge_result/27_log2exp_pac_heatmap/27_gene_list.txt", sep = "\t")
rt_ROC <- read.table(file = "/Users/stead/Desktop/GDC/LUAD/ROC/ROC_P/gene_list_ROC.txt", sep = "\t")
rt_SUR <- read.table(file = "/Users/stead/Desktop/GDC/LUAD/survival/LUAD_pvalue.tsv", header = T, row.names = NULL, sep = "\t")

rt_ROC_T <- merge(rt_ROC, rt_T, by = 1)
rt_ROC_SUR <- merge(rt_ROC, rt_SUR, by = 1)
rt_SUR_T <- merge(rt_SUR, rt_T, by =1)
rt_ROC_T_DEG <- merge(rt_ROC_T, rt_DEG, by = 1)
rt_SUR_T_DEG <- merge(rt_SUR_T, rt_DEG, by = 1)
rt_SUR_T_DEG_ROC <- merge(rt_SUR_T_DEG, rt_ROC, by = 1)
write.table(rt_SUR_T_DEG, file = "rt_SUR_T_DEG.txt", col.names = T, row.names = T, sep = "\t")
write.table(rt_ROC_T_DEG,file = "rt_ROC_T_DEG.txt", col.names = T, row.names = T, sep = "\t")
write.table(rt_SUR_T_DEG_ROC, file = "rt_SUR_T_DEG_ROC.txt", col.names = T, row.names = T, sep = "\t")
