theme_coord <-  theme(plot.title = element_text(size = 15, face="bold", hjust = 0.5),
        axis.title.x = element_text(size = 15, face="bold", color = "black"),
        axis.text.x = element_text(size = 15, color = "black"),
        axis.title.y = element_text(size = 15, face="bold", color = "black", angle = 90),
        axis.text.y = element_text(size = 10, color = "black", angle = 1),
        legend.title = element_text(colour = 'black', angle = 1, size = 15, hjust = 2, vjust =3, face = 'bold'),
        legend.text = element_text(colour = 'black', angle = 1, size = 15, hjust = 2, vjust = 3, face = 'bold'),
        legend.position = "bottom", legend.justification=c(1, 1),
        strip.text.x = element_text(size = 15, face="bold"),
        strip.text.y = element_text(size = 15, face="bold"))
